# THIS FILE IS AUTOMATICALLY GENERATED
# Project: C:\Users\Tymek\Documents\EE\Clock\CYBLE-224110-00_clock_firmware\CYBLE-224110-00_Clock\BLE_OTA_UpgradableStackExample_Launcher01.cydsn\BLE_OTA_UpgradableStackExample_Launcher01.cyprj
# Date: Wed, 31 Jul 2019 20:50:49 GMT
#set_units -time ns
create_clock -name {CyRouted1} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/dsi_in_0}]]
create_clock -name {CyILO} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/ilo}]]
create_clock -name {CyLFCLK} -period 31250 -waveform {0 15625} [list [get_pins {ClockBlock/lfclk}]]
create_clock -name {CyIMO} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/imo}]]
create_clock -name {CyHFCLK} -period 20.833333333333332 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/hfclk}]]
create_clock -name {CySYSCLK} -period 41.666666666666664 -waveform {0 10.4166666666667} [list [get_pins {ClockBlock/sysclk}]]


# Component constraints for C:\Users\Tymek\Documents\EE\Clock\CYBLE-224110-00_clock_firmware\CYBLE-224110-00_Clock\BLE_OTA_UpgradableStackExample_Launcher01.cydsn\TopDesign\TopDesign.cysch
# Project: C:\Users\Tymek\Documents\EE\Clock\CYBLE-224110-00_clock_firmware\CYBLE-224110-00_Clock\BLE_OTA_UpgradableStackExample_Launcher01.cydsn\BLE_OTA_UpgradableStackExample_Launcher01.cyprj
# Date: Wed, 31 Jul 2019 20:50:45 GMT
